theme: jekyll-theme-cayman
title: Postgrad Medicine Study Notes
description: Wollemia is a genus of coniferous trees in the family Araucariaceae known only through fossil records until 1994, when the species Wollemia nobilis was discovered in a temperate rainforest wilderness area growing in a remote series of narrow, steep-sided, sandstone gorges in Wollemi National Park, NSW, Australia.
